sonar.projectKey=projet_micro
sonar.projectName=projet_micro
sonar.sourceEncoding=UTF-8

sonar.sources=eureka/src,gateway/src,microservice_authentification/src,microservice_products/src,microservice_Commande/src,microservice_forum/src,microservice_reclamation/src,microservice_events/src,E-Commerce Platform Template/src
sonar.exclusions=**/target/**,**/node_modules/**,**/*.spec.ts,**/*.test.ts,**/*.d.ts
