apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-commande
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-commande
  template:
    metadata:
      labels:
        app: microservice-commande
    spec:
      containers:
        - name: microservice-commande
          image: mohamedazizsaid/microservice_Commande:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-commande
spec:
  selector:
    app: microservice-commande
  ports:
    - port: 8086
      targetPort: 8086
